default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rails-watch-list_development
#comment
test:
  <<: *default
  database: rails-watch-list_test
